spring.application.name=movie-service
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
?
security.jwt.key=moviereservationsystemsecretkey12MiniManiDevelopemntPurpose

spring.autoconfigure.exlude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.data.mongodb.uri=mongodb+srv://mani:tItUxI4cW6SXBtlj@moviereservation.eosi83d.mongodb.net/reservation?appName=MovieReservation

spring.liquibase.enabled=false

spring.datasource.url=postgresql://neondb_owner:npg_7ezD0frNFsIP@ep-raspy-shape-amtcm7rp-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=your_user
spring.datasource.password=your_password

#validate in prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect