spring.application.name=movie-service
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
?
security.jwt.key=grkmd

spring.autoconfigure.exlude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.data.mongodb.uri=mongodb+srv://mani:tItUxI4cW6SXBtlj@moviereservation.eosi83d.mongodb.net/reservation?appName=MovieReservation

spring.datasource.url=jdbc:h2:mem:testdb
#jdbc:h2:file:/data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.liquibase.enabled=false